stages:
  - build
  - lint
  - deploy

lint:
  stage: lint
  script:
    - echo "Lint helm chart"
    - helm3 lint helloworld-kotlin/

deploy_helm_chart: 
  stage: deploy
  script:
    - helm3 install helloworld-kotlin ./helloworld-kotlin/
