{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloworld-kotlin.serviceAccountName" . }}
  labels:
{{ include "helloworld-kotlin.labels" . | nindent 4 }}
{{- end -}}
